name: Deploy to Streamlit

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Streamlit Application
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.bot_token }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          REPO_NAME: ${{ secrets.REPO_NAME }}
          TOKEN_REPO: ${{ secrets.TOKEN_REPO }}
        run: |
          streamlit run main.py --server.headless true || echo "Error detected" > error_log.txt
