name: Deploy to Streamlit

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install streamlit

      - name: Trigger Streamlit Redeployment
        env:
          STREAMLIT_APP_NAME: ${{ secrets.STREAMLIT_APP_NAME }}
        run: |
          echo "🚀 Triggering Streamlit redeployment..."
          curl -X POST \
            -H "Content-Type: application/json" \
            -d "{\"app_name\": \"$STREAMLIT_APP_NAME\"}" \
            https://sharing.streamlit.io/api/v1/deploy || { echo "❌ Failed to trigger Streamlit deployment"; exit 1; }
