name: Deploy to Streamlit

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          set -e  # Exit if any command fails
          pip install --upgrade pip
          pip install -r requirements.txt || { echo "❌ Failed to install dependencies"; exit 1; }

      - name: Configure Git Identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Debug GitHub Actions Token
        run: |
          echo "🔍 Checking if GitHub Actions has proper permissions..."
          echo "🔑 Current Token (First 8 Chars): ${TOKEN_REPO:0:8}"
          curl -H "Authorization: token ${TOKEN_REPO}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}



      - name: Restart Streamlit Deployment
        env:
          TOKEN_REPO: ${{ secrets.TOKEN_REPO }}
        run: |
          set -e  # Exit if any command fails
          echo "🔄 Triggering Streamlit to update..."
          git remote set-url origin https://x-access-token:${TOKEN_REPO}@github.com/${{ github.repository }}.git
          git pull origin main || { echo "❌ Failed to pull latest changes"; exit 1; }
          git commit --allow-empty -m "Trigger Streamlit redeploy" || { echo "❌ Failed to create empty commit"; exit 1; }
          git push origin main || { echo "❌ Failed to push changes to GitHub"; exit 1; }
