name: Deploy to Streamlit
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Use latest version
        with:
          fetch-depth: 0  # Fetches full history

      - name: Set up Python
        uses: actions/setup-python@v5  # Use latest version
        with:
          python-version: '3.10'
          cache: 'pip'  # Cache pip dependencies

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Validate Code (optional)
        run: |
          # Add any validation checks here
          # For example:
          # flake8 .  # Code style check
          # mypy .    # Type checking
          # python -m pytest  # Run tests
