name: Run Discord Bot
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cancel-previous-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Workflow Runs
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const workflowId = context.workflow;

            try {
              // List running workflow runs
              const runningRuns = await github.rest.actions.listWorkflowRuns({
                owner,
                repo,
                workflow_id: workflowId,
                status: 'in_progress'
              });

              // Cancel all previous runs except the current one
              for (const run of runningRuns.data.workflow_runs) {
                if (run.id !== context.runId) {
                  console.log(`Cancelling workflow run ${run.id}`);
                  await github.rest.actions.cancelWorkflowRun({
                    owner,
                    repo,
                    run_id: run.id
                  });
                }
              }
            } catch (error) {
              console.error('Error cancelling previous runs:', error);
            }

  run-discord-bot:
    needs: cancel-previous-runs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Discord Bot with Improved Process Management
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          REPO_NAME: ${{ secrets.REPO_NAME }}
          TOKEN_REPO: ${{ secrets.TOKEN_REPO }}
        run: |
          # Validate required secrets
          if [ -z "$DISCORD_BOT_TOKEN" ] || [ -z "$OPENAI_API_KEY" ] || [ -z "$REPO_NAME" ] || [ -z "$TOKEN_REPO" ]; then
            echo "❌ ERROR: One or more required secrets are missing!"
            exit 1
          fi

          # Robust bot running with process management
          python discord_bot.py &
          BOT_PID=$!

          # Wait for 1 hour (3600 seconds) to prevent unnecessary long-running workflows
          sleep 3600

          # Gracefully terminate the bot
          kill $BOT_PID
          wait $BOT_PID
