name: Run Discord Bot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cancel-previous:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous bot runs
        uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{ secrets.TOKEN_REPO }}

  run-bot:
    needs: cancel-previous
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug Secrets
        run: |
          echo "🔍 Checking if secrets are available..."
          echo "DISCORD_BOT_TOKEN=${{ secrets.bot_token }}" | sed 's/./& /g'
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" | sed 's/./& /g'
          echo "NEWS_API_KEY=${{ secrets.NEWS_API_KEY }}" | sed 's/./& /g'
          echo "REPO_NAME=${{ secrets.REPO_NAME }}" | sed 's/./& /g'
          echo "TOKEN_REPO=${{ secrets.TOKEN_REPO }}" | sed 's/./& /g'

      - name: Run Discord Bot
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.bot_token }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          REPO_NAME: ${{ secrets.REPO_NAME }}
          TOKEN_REPO: ${{ secrets.TOKEN_REPO }}
        run: |
          # Final check before running
          if [ -z "$DISCORD_BOT_TOKEN" ] || [ -z "$OPENAI_API_KEY" ] || [ -z "$REPO_NAME" ] || [ -z "$TOKEN_REPO" ]; then
            echo "❌ ERROR: One or more required secrets are missing!"
            exit 1
          fi

          while true; do python discord_bot.py; sleep 10; done
